# 删除或注释掉原来的 remote_theme: pages-themes/architect@v0.2.0
remote_theme: just-the-docs/just-the-docs
# 关闭 Just the Docs 的默认页脚版权提示
aux_links_new_tab: true
title: 浙江省乐清中学信奥队
footer_content: ""
plugins:
  - jekyll-remote-theme
